### ISSUE TITLE
Ros Indigo support?

### ISSUE THREAD

**Issue by bpinaya** [voxel-dot-at/sentis_tof_m100_pkg#1]
I was wondering if there is support for Ros Indigo, I am trying to build it with no success. Some tips will be appreciated :)

**Comment by svogl** [comment]
Hi Benjamin,
could you give us more information on your build environment and the 
actual error messages you see?
thanks
Simon

On 07/04/16 07:27, Benjamin Pinaya wrote:

> I was wondering if there is support for Ros Indigo, I am trying to 
> build it with no success. Some tips will be appreciated :)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/voxel-dot-at/sentis_tof_m100_pkg/issues/1

## 

VoXel Interaction Design  |  http://www.voxel.at/
DI Dr.techn. Simon Vogl   |  simon@voxel.at
Tomaschekweg 46           |  +43 650 2323 555
A-4040 Linz - Austria     |
Office address: Industriezeile 35, 4020 Linz (2nd floor)

**Comment by angelmerino** [comment]
Hi Benjamin,
This ROS package uses an old api for the m100.
We have another package that uses the BltToF api from Bluetechnix -> https://github.com/voxel-dot-at/bta_ros
That one works with Indigo without problems with the BltToF api v1.6.1. 
There is a new api version v2.1 but the bta_ros package should be adapted.
Best regards

**Comment by bpinaya** [comment]
Thank you for the quick reply! I am checking the other repo.
